config/routes.rb
Hrm::Application.routes.draw do
  namespace :admin do
    
  end

  get "home/index"
  get "search" => "search#index"
  get "salary" => "salary#index"

  get 'checks' => "checks#index" ,as: :checks
  post 'checks/import' => "checks#import"
  post 'checks/exception' => "checks#exception"

  resources :attachments

  resources :experiences

  resources :trains

  resources :performances

  resources :jobs

  resources :groups

  resources :educations

  resources :employees

  resources :helps

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    root :to => "home#index"
  
    resources :users
    resources :settings

    get '/checks' => "checks#index"
    get '/checks/mark'
    get '/checks/list'
    post "/checks/setting"
  end

  match '/sign_up',           to: 'users#new',         via: 'get'
  match '/sign_in',           to: 'sessions#new',      via: 'get'
  match '/sign_out',          to: 'sessions#destroy',  via: 'delete'
  match '/user/register',     to: 'users#create' ,     via: 'post'
  match '/user/verify/:email',to: 'users#verify' ,     via: 'get', as: :user_verify
  match '/user/active'       ,to: 'users#active' ,     via: 'get', as: :user_active

  
  match "/:username",         to: "users#show" ,       via: 'get',    as: :user_home
  match "/:username/msg",     to: "users#msg" ,        via: 'get',    as: :user_msg
  match "/:username/setting", to: "users#edit" ,       via: 'get',    as: :user_setting
  match '/:username/update',  to: 'users#update' ,     via: 'patch',  as: :user_update
  match "/:username/destroy", to: "users#destroy",     via: 'delete', as: :user_delete
  match "/:username/reset",   to: "users#reset",       via: 'post', as: :user_reset

  

  root 'home#index'

  

end

app/models/train.rb
class Train < ActiveRecord::Base
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render action: 'show', status: :created, location: @train }
      else
        format.html { render action: 'new' }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:name, :employee_id, :keynote, :date, :duration, :address, :must)
    end
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :keynote %><br>
    <%= f.text_field :keynote %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :must %><br>
    <%= f.check_box :must %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<h1><%= t("train.train")%></h1>

<table class="table table-striped table-hover table-bordered " >  <thead>
  <thead>
    <tr>
      <th>培训主题</th>
      <th>主讲人</th>
      <th>关键内容</th>
      <th>日期</th>
      <th>时长(分)</th>
      <th>地点</th>
      <th>是否必须?</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.name %></td>
        <td><%= train.employee.name %></td>
        <td><%= train.keynote %></td>
        <td><%= train.date %></td>
        <td><%= train.duration %></td>
        <td><%= train.address %></td>
        <td><%= train.must %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @train.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @train.employee_id %>
</p>

<p>
  <strong>Keynote:</strong>
  <%= @train.keynote %>
</p>

<p>
  <strong>Date:</strong>
  <%= @train.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @train.duration %>
</p>

<p>
  <strong>Address:</strong>
  <%= @train.address %>
</p>

<p>
  <strong>Must:</strong>
  <%= @train.must %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>