config/routes.rb
Hrm::Application.routes.draw do
  namespace :admin do
    
  end

  get "home/index"
  get "search" => "search#index"
  get "salary" => "salary#index"

  get 'checks' => "checks#index" ,as: :checks
  post 'checks/import' => "checks#import"
  post 'checks/exception' => "checks#exception"

  resources :attachments

  resources :experiences

  resources :trains

  resources :performances

  resources :jobs

  resources :groups

  resources :educations

  resources :employees

  resources :helps

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    root :to => "home#index"
  
    resources :users
    resources :settings

    get '/checks' => "checks#index"
    get '/checks/mark'
    get '/checks/list'
    post "/checks/setting"
  end

  match '/sign_up',           to: 'users#new',         via: 'get'
  match '/sign_in',           to: 'sessions#new',      via: 'get'
  match '/sign_out',          to: 'sessions#destroy',  via: 'delete'
  match '/user/register',     to: 'users#create' ,     via: 'post'
  match '/user/verify/:email',to: 'users#verify' ,     via: 'get', as: :user_verify
  match '/user/active'       ,to: 'users#active' ,     via: 'get', as: :user_active

  
  match "/:username",         to: "users#show" ,       via: 'get',    as: :user_home
  match "/:username/msg",     to: "users#msg" ,        via: 'get',    as: :user_msg
  match "/:username/setting", to: "users#edit" ,       via: 'get',    as: :user_setting
  match '/:username/update',  to: 'users#update' ,     via: 'patch',  as: :user_update
  match "/:username/destroy", to: "users#destroy",     via: 'delete', as: :user_delete
  match "/:username/reset",   to: "users#reset",       via: 'post', as: :user_reset

  

  root 'home#index'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :job

	@level = 0

	def self.level=(level)
		@level = level
	end

	def self.level
		@level
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        flash[:success] = 'Group was successfully updated.'
        format.html { redirect_to groups_url }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_id, :employee_id, :name,:salary)
    end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="well">
  <div class="field">
    <%= f.label :group_id, t("group.parent") %>
    <%= f.collection_select :group_id, Group.all, :id, :name, { :prompt => '公司顶层' } %>
  </div>
  <div class="field">
    <%= f.label :name,t("group.name") %>
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :salary,t("group.salary") %>
    <div class="input-group input-prepend input-append ">
      <span class="add-on">￥</span>
      <%= f.number_field :salary ,:class => "input-medium" %>
      <span class="add-on">.00</span>
    </div>
    
  </div>
  <div class="actions">
    <%= f.submit  :class => "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/groups/_tree.html.erb
<% 
Group.where(:group_id => id).each do |gp| %>

<%= link_to 'Edit', edit_group_path(gp), :class => "btn btn-mini" %>
<%= link_to 'Destroy', gp, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-mini" %>
<span  >|-&nbsp;<%= ("\\___" * Group.level) %></span>
<span class="label label-info" ><%=gp.name%></span>
<br />
<%= if Group.where(:group_id => gp.id).count > 0
		Group.level += 1
		 tmpl = render 'tree',:id => gp.id
	else
		Group.level = 0
		""
	end
 %>


<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1><%= t("group.group_list")%></h1>

<div class="group_tree">
  <%= render 'tree', :id => nil %>
</div>

app/views/groups/new.html.erb
<h1><%= t("group.add_group")%></h1>

<%= render 'form' %>