config/routes.rb
Hrm::Application.routes.draw do
  namespace :admin do
    
  end

  get "home/index"
  get "search" => "search#index"
  get "salary" => "salary#index"

  get 'checks' => "checks#index" ,as: :checks
  post 'checks/import' => "checks#import"
  post 'checks/exception' => "checks#exception"

  resources :attachments

  resources :experiences

  resources :trains

  resources :performances

  resources :jobs

  resources :groups

  resources :educations

  resources :employees

  resources :helps

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    root :to => "home#index"
  
    resources :users
    resources :settings

    get '/checks' => "checks#index"
    get '/checks/mark'
    get '/checks/list'
    post "/checks/setting"
  end

  match '/sign_up',           to: 'users#new',         via: 'get'
  match '/sign_in',           to: 'sessions#new',      via: 'get'
  match '/sign_out',          to: 'sessions#destroy',  via: 'delete'
  match '/user/register',     to: 'users#create' ,     via: 'post'
  match '/user/verify/:email',to: 'users#verify' ,     via: 'get', as: :user_verify
  match '/user/active'       ,to: 'users#active' ,     via: 'get', as: :user_active

  
  match "/:username",         to: "users#show" ,       via: 'get',    as: :user_home
  match "/:username/msg",     to: "users#msg" ,        via: 'get',    as: :user_msg
  match "/:username/setting", to: "users#edit" ,       via: 'get',    as: :user_setting
  match '/:username/update',  to: 'users#update' ,     via: 'patch',  as: :user_update
  match "/:username/destroy", to: "users#destroy",     via: 'delete', as: :user_delete
  match "/:username/reset",   to: "users#reset",       via: 'post', as: :user_reset

  

  root 'home#index'

  

end

app/models/help.rb
class Help < ActiveRecord::Base
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :set_help, only: [:show, :edit, :update, :destroy]

  # GET /helps
  # GET /helps.json
  def index
    @helps = Help.all
  end

  # GET /helps/1
  # GET /helps/1.json
  def show
  end

  # GET /helps/new
  def new
    @help = Help.new
  end

  # GET /helps/1/edit
  def edit
  end

  # POST /helps
  # POST /helps.json
  def create
    @help = Help.new(help_params)

    respond_to do |format|
      if @help.save
        format.html { redirect_to @help, notice: 'Help was successfully created.' }
        format.json { render action: 'show', status: :created, location: @help }
      else
        format.html { render action: 'new' }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helps/1
  # PATCH/PUT /helps/1.json
  def update
    respond_to do |format|
      if @help.update(help_params)
        format.html { redirect_to @help, notice: 'Help was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helps/1
  # DELETE /helps/1.json
  def destroy
    @help.destroy
    respond_to do |format|
      format.html { redirect_to helps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help
      @help = Help.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_params
      params.require(:help).permit(:title, :content)
    end
end

app/views/helps/_form.html.erb
<%= form_for(@help) do |f| %>
  <% if @help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
      <% @help.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helps/edit.html.erb
<h1>Editing help</h1>

<%= render 'form' %>

<%= link_to 'Show', @help %> |
<%= link_to 'Back', helps_path %>

app/views/helps/index.html.erb
<h1>Help Page</h1>
<ul>
    <% @helps.each do |help| %>
    <li class="">
      <h3><%= link_to help.title, help %></h3>
      post date: <%= help.updated_at %>
      <% if signed_in? && current_user.admin? %>
        <%= link_to 'Edit', edit_help_path(help) %> | 
        <%= link_to 'Destroy', help, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
    <% end %>
</ul>

  


<br>

<%= link_to 'New Help', new_help_path %>

app/views/helps/new.html.erb
<h1>New help</h1>

<%= render 'form' %>

<%= link_to 'Back', helps_path %>

app/views/helps/show.html.erb
<% provide(:title, @help.title + " | Help Page") %>
<h3><%= @help.title %></h3>
<p class="well">
  <%= @help.content %>
</p>
<%= render 'layouts/disqus' %>