config/routes.rb
Hrm::Application.routes.draw do
  namespace :admin do
    
  end

  get "home/index"
  get "search" => "search#index"
  get "salary" => "salary#index"

  get 'checks' => "checks#index" ,as: :checks
  post 'checks/import' => "checks#import"
  post 'checks/exception' => "checks#exception"

  resources :attachments

  resources :experiences

  resources :trains

  resources :performances

  resources :jobs

  resources :groups

  resources :educations

  resources :employees

  resources :helps

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    root :to => "home#index"
  
    resources :users
    resources :settings

    get '/checks' => "checks#index"
    get '/checks/mark'
    get '/checks/list'
    post "/checks/setting"
  end

  match '/sign_up',           to: 'users#new',         via: 'get'
  match '/sign_in',           to: 'sessions#new',      via: 'get'
  match '/sign_out',          to: 'sessions#destroy',  via: 'delete'
  match '/user/register',     to: 'users#create' ,     via: 'post'
  match '/user/verify/:email',to: 'users#verify' ,     via: 'get', as: :user_verify
  match '/user/active'       ,to: 'users#active' ,     via: 'get', as: :user_active

  
  match "/:username",         to: "users#show" ,       via: 'get',    as: :user_home
  match "/:username/msg",     to: "users#msg" ,        via: 'get',    as: :user_msg
  match "/:username/setting", to: "users#edit" ,       via: 'get',    as: :user_setting
  match '/:username/update',  to: 'users#update' ,     via: 'patch',  as: :user_update
  match "/:username/destroy", to: "users#destroy",     via: 'delete', as: :user_delete
  match "/:username/reset",   to: "users#reset",       via: 'post', as: :user_reset

  

  root 'home#index'

  

end

app/models/admin/setting.rb
class Admin::Setting < ActiveRecord::Base
	def self.set(name,key,val)
		@setting = Admin::Setting.where(:name => name,:key => key).first
		@setting ||= Admin::Setting.new(:name => name,:key => key)
		@setting.update_attributes(:value => val)
	end

	def self.get(name,key)
		settting = Admin::Setting.where(:name => name, :key => key).first
		settting[:value] if settting
	end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::ApplicationController
  before_action :set_admin_setting, only: [:show, :edit, :update, :destroy]

  # GET /admin/settings
  # GET /admin/settings.json
  def index
    @admin_settings = Admin::Setting.all
  end

  # GET /admin/settings/1
  # GET /admin/settings/1.json
  def show
  end

  # GET /admin/settings/new
  def new
    @admin_setting = Admin::Setting.new
  end

  # GET /admin/settings/1/edit
  def edit
  end

  # POST /admin/settings
  # POST /admin/settings.json
  def create
    @admin_setting = Admin::Setting.new(admin_setting_params)

    respond_to do |format|
      if @admin_setting.save
        format.html { redirect_to @admin_setting, notice: 'Setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/settings/1
  # PATCH/PUT /admin/settings/1.json
  def update
    respond_to do |format|
      if @admin_setting.update(admin_setting_params)
        format.html { redirect_to @admin_setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/settings/1
  # DELETE /admin/settings/1.json
  def destroy
    @admin_setting.destroy
    respond_to do |format|
      format.html { redirect_to admin_settings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_setting
      @admin_setting = Admin::Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_setting_params
      params.require(:admin_setting).permit(:name, :key, :value)
    end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_form.html.erb
<%= form_for(@admin_setting) do |f| %>
  <% if @admin_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_setting.errors.count, "error") %> prohibited this admin_setting from being saved:</h2>

      <ul>
      <% @admin_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/settings/edit.html.erb
<h1>Editing admin_setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_setting %> |
<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/index.html.erb
<h1>Listing admin_settings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_settings.each do |admin_setting| %>
      <tr>
        <td><%= admin_setting.name %></td>
        <td><%= admin_setting.key %></td>
        <td><%= admin_setting.value %></td>
        <td><%= link_to 'Show', admin_setting %></td>
        <td><%= link_to 'Edit', edit_admin_setting_path(admin_setting) %></td>
        <td><%= link_to 'Destroy', admin_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_admin_setting_path %>

app/views/admin/settings/new.html.erb
<h1>New admin_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_setting.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @admin_setting.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @admin_setting.value %>
</p>

<%= link_to 'Edit', edit_admin_setting_path(@admin_setting) %> |
<%= link_to 'Back', admin_settings_path %>